// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcialFJCO.Infraestructure.Data;

#nullable disable

namespace ParcialFJCO.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParcialFJCO.Domain.Entities.AlertaAire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("AlertasAire");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaHora = new DateTime(2026, 5, 19, 3, 45, 0, 0, DateTimeKind.Utc),
                            Mensaje = "La calidad del aire es poco saludable para grupos sensibles (niños, adultos mayores, personas con enfermedades respiratorias).",
                            Nivel = "Moderada",
                            SensorId = 1
                        },
                        new
                        {
                            Id = 2,
                            FechaHora = new DateTime(2026, 5, 19, 3, 50, 0, 0, DateTimeKind.Utc),
                            Mensaje = "Nivel de contaminación extremadamente alto. Riesgo severo para la salud.",
                            Nivel = "Extrema",
                            SensorId = 2
                        });
                });

            modelBuilder.Entity("ParcialFJCO.Domain.Entities.LecturaAire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CO2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PM10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PM2_5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("LecturasAire");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CO2 = 600m,
                            FechaHora = new DateTime(2026, 5, 19, 3, 40, 0, 0, DateTimeKind.Utc),
                            PM10 = 20m,
                            PM2_5 = 12m,
                            SensorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CO2 = 900m,
                            FechaHora = new DateTime(2026, 5, 19, 3, 45, 0, 0, DateTimeKind.Utc),
                            PM10 = 120m,
                            PM2_5 = 80m,
                            SensorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CO2 = 6001m,
                            FechaHora = new DateTime(2026, 5, 19, 3, 50, 0, 0, DateTimeKind.Utc),
                            PM10 = 60m,
                            PM2_5 = 40m,
                            SensorId = 2
                        });
                });

            modelBuilder.Entity("ParcialFJCO.Domain.Entities.SensorCalidadAire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("TipoGas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SensoresCalidadAire");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Activo",
                            TipoGas = "PM2.5/PM10/CO2",
                            Ubicacion = "Planta 1 - Zona A"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Activo",
                            TipoGas = "PM2.5/CO2",
                            Ubicacion = "Planta 1 - Zona B"
                        });
                });

            modelBuilder.Entity("ParcialFJCO.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$NfCjQSpWiylUK5OzOypVteoQ4kBdr9mX7b6Gs/x1Oj9101PjF1c32",
                            Role = "Admin",
                            Username = "usuarioAdmin"
                        });
                });

            modelBuilder.Entity("ParcialFJCO.Domain.Entities.AlertaAire", b =>
                {
                    b.HasOne("ParcialFJCO.Domain.Entities.SensorCalidadAire", "Sensor")
                        .WithMany("Alertas")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("ParcialFJCO.Domain.Entities.LecturaAire", b =>
                {
                    b.HasOne("ParcialFJCO.Domain.Entities.SensorCalidadAire", "Sensor")
                        .WithMany("Lecturas")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("ParcialFJCO.Domain.Entities.SensorCalidadAire", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Lecturas");
                });
#pragma warning restore 612, 618
        }
    }
}
